version: '3'
networks:
  app-network: null
services:
  mysql:
    platform: linux/amd64
    image: 'mysql:8.0.29'
    container_name: 'mysql_${APP_NAME}'
    restart: unless-stopped
    tty: true
    command: --sql_mode=''
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ma
      MYSQL_USER: homestead
      MYSQL_PASSWORD: homestead
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network
